import "./globals.css";
import { LazyMotion, domAnimation } from "framer-motion";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <LazyMotion features={domAnimation}>
                <body>{children}</body>
            </LazyMotion>
        </html>
    );
}
